### ISSUE TITLE
Copy galleries from old site

### ISSUE THREAD

**Issue by miki725** [millbrook/millbrook.github.io#1]
Probably better to port them to flickr so that galleries can be embedded without storing jpg files in repo

**Comment by miki725** [comment]
@aliarje would you be able to create flicks account for millbrook with millbrook email address? I dont have access to that email. Ill be able to copy galleries over after that

**Comment by aliarje** [comment]
Miro, I'm away from my computer this weekend. Will do on Monday.

**Comment by aliarje** [comment]
Hey Miro, I got back early and set up the Flickr acct:

Username: Mill Brook
Password: 16ForestRoad  (the school address)
Birthdate: 1.1.1950  (had to give one)
Email: general@millbrookcivic.com

**Comment by miki725** [comment]
thanks @aliarje 

fyi. when you reply to github comments, they are publicly visible... in this case at https://github.com/millbrook/millbrook.github.io/issues/1. so any shared passwords are publicly visible which is not desired.

to share a password securely you can use a service like https://onetimesecret.com/ and then send me a private email with the link. after I will access it that link will become invalid.

anyway, I was not able to login to flicks. can you reset the password asap to avoid anybody else logging in and send me the credentials as described above

thanks

**Comment by aliarje** [comment]
How about you write to me from your email address and not github?

**Comment by aliarje** [comment]
Can you erase that message? You should have told me this to begin with.

**Comment by miki725** [comment]
@aliarje its much easier for me to keep track of things in github since each issue has its own thread. that way I dont have to search for multiple emails.

it might be easier for you to send comments in github interface vs replying in email. each email you receive from github should have a footer something like:

```
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
```

**view it on GitHub** will have a link to the github issue where you can directly reply.
