### ISSUE TITLE
Trim menu items

### ISSUE THREAD

**Issue by miki725** [millbrook/millbrook.github.io#14]
Can we combine about and history pages? Possibly even with civic board? all those could apply under about page? there are quite a few links now and in some screen sizes some words are starting to be truncated:

![image](https://user-images.githubusercontent.com/932940/38442114-2f4edb32-39b5-11e8-8d2e-c79663beea42.png)

cc @aliarje

**Comment by aliarje** [comment]
Yes, fine to combine History and About pages under About. Begin with History and follow with pictures, or put a link to Community Photos after the history text. 
Need to keep Civic page separate.

**Comment by miki725** [comment]
ok. will adjust #16 thanks

**Comment by miki725** [comment]
leaving civic board does not leave enough space:

![image](https://user-images.githubusercontent.com/932940/38443188-d8e86e4e-39b8-11e8-8da9-a3de8f116aa8.png)

**Comment by miki725** [comment]
updated live site. you can take a look

**Comment by aliarje** [comment]
Looks great! 
Do we need captcha on contact forms?

**Comment by miki725** [comment]
no. see https://github.com/millbrook/millbrook.github.io/issues/11
