### ISSUE TITLE
Add contact details about county commissioner committee

### ISSUE THREAD

**Issue by miki725** [millbrook/millbrook.github.io#19]

**Comment by aliarje** [comment]
Hi Miro,
I'm waiting for a reply from Natalie Cange that the email address she gave
me is operational.
Thank you and great to see you at the meeting. You should really think
about joining the board.
Ali

**Comment by aliarje** [comment]
**POLICE COMMISSIONER FORMS NEW COMMUNITY COUNCIL**

Nassau County Police Commissioner Patrick Ryder officially kicked into gear his Community Council, a police task force with a subdivision in each of the county’s 19 legislative districts.

Ryder and County Executive Laura Curran worked with the county’s 19 legislators to select residents who “have a finger on the pulse of their communities,” Curran said. On April 9 at the Cradle of Aviation Museum, a room full of residents were sworn into their positions.
 
The members of the community council have agreed to volunteer their time to address the specific issues plaguing their community. They will be meeting with county police and their legislator, periodically, to develop plans of action and discuss what can be done to curb local crime. Eventually, an executive community council will be chosen to oversee the other 19 groups.

“When you speak to people from different communities, that’s when you start to understand each other's cultures, and understand what the needs are for each community,” Ryder said. “And that’s what we intend to do with this community council.”

The representative from Mill Brook is Natalie Cange. If you have an issue you would like addressed, you can send it to general@millbrookcivic.com and we will forward it to Natalie, or send it directly to NatalieCangeCCC@gmail.com.
