### ISSUE TITLE
Two new website posts

### ISSUE THREAD

**Issue by aliarje** [millbrook/millbrook.github.io#20]
**Beautification Event**
Mill Brook's environmental expert, Tricia Vanderbeck, led a group of South High School students in tending our community gardens. The civic association provided the supplies, but Trish and her hard-working volunteers made it happen.
Our next garden event will be in the fall. Please come out and help us keep our community beautiful. Watch this website for the November date.
(upload 3 most recent pics on Flickr)

**Community Facebook Page**
The civic association Facebook page had to be taken down due to technical issues. You are invited to ask to join the Mill Brook Community Facebook page. Once admitted, you can post news your neighbors want to know about and join in the conversations.
(https://www.facebook.com/groups/178038975645012/
(Link to text Mill Brook Community Facebook page)

**Comment by miki725** [comment]
> (upload 3 most recent pics on Flickr)

@aliarje did you create new flickr album? not sure what you mean by that? do I need to link to an album in the post like in about page?

**Comment by miki725** [comment]
also updated the facebook url in the menu as well

**Comment by miki725** [comment]
4ebc0ba3255cf456151910330e8b474b03d34fa3 and 52123d7f90cafbb245ecc81bb84f1708a22a1c1f

**Comment by aliarje** [comment]
Can you put the photos in from Flickr? If not, I'll attach them here. Thnx

**Comment by aliarje** [comment]
They go with the Beautification post

**Comment by miki725** [comment]
@aliarje can you link to the specific ones. not sure which are new

**Comment by aliarje** [comment]
Don't know how to execute the link. They are the three pictures in the May
26, 2018 album on our Flickr page.
