### ISSUE TITLE
Correct dates for older posts

### ISSUE THREAD

**Issue by miki725** [millbrook/millbrook.github.io#3]

**Comment by miki725** [comment]
@aliarje can you help identifying more appropriate dates?

**Comment by aliarje** [comment]
Ah, for previous posts? Will research.

**Comment by aliarje** [comment]
2016 Planting Day  June 2, 2016
Seeking New Board Members  November 9, 2015
2015 Planting Day  May 19, 2015
2014 Planting Day  May 10, 2014
Notice from Sanitation District (add a hashtag 1 after District)  November 9, 2015
Letter from Scholarship Winner (Change to SHS Scholarship Winner)  June 28, 2015
